#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 21 07:51:15 CST 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TOP_tb_behav -key {Behavioral:sim_1:Functional:TOP_tb} -tclbatch TOP_tb.tcl -view /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sim_1/imports/pipelineCPUFPGA/TOP_tb_behav.wcfg -log simulate.log"
xsim TOP_tb_behav -key {Behavioral:sim_1:Functional:TOP_tb} -tclbatch TOP_tb.tcl -view /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sim_1/imports/pipelineCPUFPGA/TOP_tb_behav.wcfg -log simulate.log

