# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/ip/I_mem/I_mem.xci
# IP: The module: 'I_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/ip/I_mem/I_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/ip/I_mem/I_mem.xci
# IP: The module: 'I_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/ip/I_mem/I_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
