# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# IP: ip/I_mem/I_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I_mem || ORIG_REF_NAME==I_mem} -quiet] -quiet
