# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.runs/synth_1/main.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.cache/wt [current_project]
set_property parent.project_path /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/imports/CPUtests/E_6/E_6_I.coe
add_files /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/imports/CPUtests/E_7/E_7_I.coe
add_files /home/sjq/Downloads/CPUtests/E_7/E_7_I.coe
add_files /home/sjq/Downloads/CPUtests/F_1/F_1_I.coe
add_files /home/sjq/Downloads/CPUtests/F_2/F_2_I.coe
add_files /home/sjq/Downloads/CPUtests/H_1/H_1_I.coe
add_files /home/sjq/Downloads/CPUtests/F_4/F_4_I.coe
read_verilog -library xil_defaultlib {
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/ALU.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/ALU_MEM.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/BEFORE_IF.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/ID.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/ID_ALU.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/IF.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/IF_ID.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/IM.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/MEM.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/MEM_WB.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/TOP.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/Tool_clock_divider.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/WB.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/bonetime.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/debounce.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/scan_seg.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/seven_seg_map.v
  /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/new/main.v
}
read_ip -quiet /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/ip/D_mem/D_mem.xci
set_property used_in_implementation false [get_files -all /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.gen/sources_1/ip/D_mem/D_mem_ooc.xdc]

read_ip -quiet /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/ip/I_mem/I_mem.xci
set_property used_in_implementation false [get_files -all /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/sources_1/ip/I_mem/I_mem_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/constrs_1/new/cons.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/sjq/Documents/pipelineCPUFPGA/pipelineCPUFPGA.srcs/utils_1/imports/synth_1/main.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top main -part xc7a35tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
